### ISSUE TITLE
Copy Path menu item in hierarchy

### ISSUE THREAD

**Issue by rhaamo** [BluWizard10/Blu-Hierarchy#1]
I had the need for a Copy Path in the hierarchy context menu, the following code adapted a bit from https://forum.unity.com/threads/please-include-a-copy-path-when-right-clicking-a-game-object.429480/#post-2777071 do works:
```csharp
public static class CopyPathMenuItem
{
    [MenuItem("GameObject/Copy Path")]
    private static void CopyPath()
    {
        var go = Selection.activeGameObject;

        if (go == null)
        {
            return;
        }

        var path = go.name;

        while (go.transform.parent != null)
        {
            go = go.transform.parent.gameObject;
            path = string.Format("{0}/{1}", go.name, path);
        }

        EditorGUIUtility.systemCopyBuffer = path;
    }

    [MenuItem("GameObject/Copy Path", true)]
    private static bool CopyPathValidation()
    {
        // We can only copy the path in case 1 object is selected
        return Selection.gameObjects.Length == 1;
    }
}
```

I have put it right before L113 in `BluHierarchy.cs`.

I think it could be useful to add, and maybe check for a `VRCDescriptor` to get the path under the "Avatar name in hierarchy" like "Armature/Foo/Bar" instead of "My Cute Avatar/Armature/Foo/Bar"

**Comment by BluWizard10** [comment]
I can see the usefulness of this.

I'm not sure how I can check for a VRC Avatar Descriptor to get the path under the avatar name, but I'll look into it. Thanks for the suggestion!
